### ISSUE TITLE
HexoSpeller init error

### ISSUE THREAD

**Issue by okbalefthanded** [venthur/pyff#20]
I had successfully run different feedbacks among the available ones on Pyff, however while trying to run the HexoSpeller it crashs on the init phase, here's the traceback logger messages I get : 
(I'm running Pyff in PyCharm with Python2.7 on Ubuntu 14.04)

Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Warning: pandac.PandaModules is deprecated, import from panda3d.core instead
Using deprecated DirectStart interface.
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
[23509:MainThread] FB.HexoSpeller           : WARNING  Unable to open parallel port! Please install pyparallel to use it.
Process FeedbackProcess-2:
Traceback (most recent call last):
  File "/home/machina/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/machina/khadmation/pyff/src/lib/feedbackprocesscontroller.py", line 70, in run
    feedback.on_init()
  File "/home/machina/khadmation/pyff/src/FeedbackBase/MainloopFeedback.py", line 64, in on_init
    self.init()
  File "Feedbacks/HexoSpeller/HexoSpeller.py", line 110, in init
    self.load_language_model(os.path.join(language_model_folder_path, PARAMS["language_model_file"]))
  File "/home/machina/anaconda2/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[23502:MainThread] BciNetwork-127.0.0.1:12345: WARNING  Receiving from FC failed (timeout).
Traceback (most recent call last):
  File "/home/machina/khadmation/pyff/src/GUI.py", line 123, in sendinit
    for name, value in d.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'

**Comment by sarah-hosni** [comment]
Hi..I am sorry I won't leave a solution to ur problem..as I am still in the phase of "successfully" running pyff ..
It is just that at laaast I found someone I can ask about it..as there is almost no support at all..

I am running pyff on 2 machines..both Windows..one 32 bit and one 64 bit..I keep getting the error : " No open ipc channel available"..among other errors and warnings of course..but my main problem now is that the Feedback controller doesn't seem to be able to communicate..and when I press "send init" after selecting any feedback interface I get this error..
For example when I start puff, choose BoringClock..press "sendInit"
This is what I get (summary):
BciNetwork initialized
Receiving from FC failed (timeout)
Did not recieve answer on get_variables
For name, value in d.iteritems ()  : 
AttributeError: 'NoneType' object has no attribute 'iteritems'

Feedback Controller : ERROR  couldn't send data to feedback

Self.ipc channel.send_message(signal) raise exception ("no open ipc channel available")
I will really appreciate if u help me..
Sarah

**Comment by okbalefthanded** [comment]
Because of a bug raised by pyOpenGL 3 with VisionEgg on windows I switched to Ubuntu, currently I'm using Pyff on Ubuntu 14.04 LTS, I had encountered several problems when I tried to run it on windows.

The "NoneType" error is raised by the GUI process when it executes _sendinit_ method, the main raison you get it is that the FeedbackController (FC) failed to create/initialize the feedback, and for the IPC It could be that the port (12347) is taken.

**Comment by sarah-hosni** [comment]
Ok..Thank you very much for your reply..
I c u recommend I use puff with ubuntu..I have no experience with Linux..but I may try..in order to get pyff to work..
A VIP question..Will I be able to install matlab on ubuntu..and make the communication between puff and matlab still..?? And if there is a toolbox that I use with matlab..Will it still be available??
I am terrified to walk through all this and find a bad surprise at the end...I already spent so much time trying to make pyff work..:(

**Comment by sarah-hosni** [comment]
Another thing pls..does pyff need a pc with parallel port to work?? Or can I run it on my laptop??

**Comment by okbalefthanded** [comment]
1. Matlab is availble on Linux too, I didn't try it so far but I think it's not too complicated.
2. In order to use pyff with Matlab, the BBCI group (the laboratory behind Pyff) provides a complete toolbox for offline & online BCI experiments, and it has the same name as the lab BBCI, which provides functions that communicate with the Feedback Controller, here also the documentation and support are weak, unfortunately I didn't try it out. (I'm willing to). you can check the toolbox via this link:
   https://github.com/bbci/bbci_public
3. Most of the feedback availble with Pyff use the parallel port for marker writing, it's not that crucial since a method that uses UDP sockets to do the same job is also avaible in the base class "Feedback".
   If you run Pyff on windows a parallel port module is provided with the framework that only function on windows, in case of Linux a laptop without a parallel port will imply that you use the "send_udp" method instead of "send_parallel". I'm currently working on that since my laptop lacks a parallel port.

**Comment by sarah-hosni** [comment]
Thank you..I really appreciate it..since I am totally lost..
"Parallel port module" but there must be a physical parallel port present..right?? 

I used pyff on a win 64 bit laptop..an error concerning inpout32dll showed up..although I followed the recommended steps..

I then brought an old pc with parallel port..and then the ipc failed error appeared..with the Feedback controller unable to communicate with any feedback..and the Feedback failing to initialize as I explained before...

I wish u luck..
I hope you keep contact with me and remain this generous..since it seems we are the only 2 people using pyff in the world!!!!  May I ask what eeg acquisition device are u using??

**Comment by okbalefthanded** [comment]
Did you install the 64 bit input dll ? it's avaible in the tools folder.

I'm using the gtec gUSBamp as EEG acquisition device

**Comment by sarah-hosni** [comment]
I am not sure what do u mean by install..I copied it in the folder system32..also..the error is asking about inpout32.dll..not 64..
As I understood there is some executable u run, which I did..and then the inpout32.ell can be used for a 64 bit system...I did this..copied the files both..the 32 and 64..and still no use..

**Comment by sarah-hosni** [comment]
*.dll

**Comment by okbalefthanded** [comment]
what I mean by install is to run the executable in the tools/x64/32bits folder, In my experience I didn't encounter problems with the parallel port when I was using pyff on windows but it was too limited, as I remember I run the boring clock feedback successfully, but failed with the rest of feedbacks.
